function J = jacobian_function(x, params)
    if nargin ~= 2
        error('jacobian_function:InvalidInputCount', ...
            'jacobian_function expects exactly two inputs.');
    end
    if numel(x) ~= 5
        error('jacobian_function:InvalidStateVector', ...
            'Expected a 5-element active state vector, got %d elements.', numel(x));
    end

    J = [ ...
        1,  -1, 0, 0, 0; ...
       -params.turns_ratio / params.burden_resistance, ...
        params.turns_ratio / params.burden_resistance, 1, 0, 0; ...
        0,   0, 0, -params.magnetizing_inductance, 1; ...
       -1 / params.burden_resistance, 1 / params.burden_resistance, 1, -1, 0; ...
        1,   1, 0, 0, 0];
end
