function stateInfo = state_definition()
    stateInfo = struct();
    stateInfo.names = {'v1', 'v2', 'v3', 'v4', 'ip', 'iL1', 'iL2', 'iL3', ...
        'im', 'lambda', 'e'};
    stateInfo.num_states = numel(stateInfo.names);
    stateInfo.index = struct( ...
        'v1', 1, ...
        'v2', 2, ...
        'v3', 3, ...
        'v4', 4, ...
        'ip', 5, ...
        'iL1', 6, ...
        'iL2', 7, ...
        'iL3', 8, ...
        'im', 9, ...
        'lambda', 10, ...
        'e', 11);
    stateInfo.description = ['Reduced core state using the directly supported ' ...
        'network and flux equations on the main branch.'];
end
