function stateInfo = state_definition()
    stateInfo = struct();
    stateInfo.names = {'v1', 'v2', 'v3', 'v4', 'ip', 'iL1', 'iL2', 'iL3', ...
        'im', 'lambda', 'e', 'y1', 'y2', 'y3', 'y4', 'ibm'};
    stateInfo.num_states = numel(stateInfo.names);
    stateInfo.index = struct( ...
        'v1', 1, ...
        'v2', 2, ...
        'v3', 3, ...
        'v4', 4, ...
        'ip', 5, ...
        'iL1', 6, ...
        'iL2', 7, ...
        'iL3', 8, ...
        'im', 9, ...
        'lambda', 10, ...
        'e', 11, ...
        'y1', 12, ...
        'y2', 13, ...
        'y3', 14, ...
        'y4', 15, ...
        'ibm', 16);
    stateInfo.description = ['Full assignment state including node voltages, ' ...
        'branch currents, flux, nonlinear auxiliary variables, and modeled burden current.'];
end
